apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-task
spec:
  stepTemplate:
    env:
      - name: BUILD_NUMBER
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']
  steps:
    - name: simple-step
      image: ubuntu
      command: ["/bin/bash", "-c"]
      args:
        - echo -e "Start Pipeline Run - Build $BUILD_NUMBER";
          sleep 30;
          echo "Build $BUILD_NUMBER Complete";
          cat /cd-config/toolchain.json
          
      volumeMounts:
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
        - key: toolchain.json
          path: toolchain.json
